spring:
  # DESACTIVAR Flyway TOTALMENTE
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/patronesiot
    username: postgres
    password: pos
  jpa:
    hibernate:
      ddl-auto: update  # JPA crea tablas SOLO
    show-sql: true
    properties:
      show-sql: true
    autoconfigure:
      exclude:
        org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    defer-datasource-initialization: true

server:
  port: 8080

alert:
  temperature:
    min: 2.0
    max: 30.0
  humidity:
    min: 30.0
    max: 80.0
